### PR TITLE
Add highlights layer to svg.

### PR DESCRIPTION
**Pull request by tttppp**
This was definitely causing the first issue.  I don't know if there are more to come, and the map will take an hour to get through the cache. At least we shouldn't have to wait 30 days! :-)

### CODE REVIEW

**Comment by zond** [comment]
Thanks! I'll deploy soon!

**Comment by zond** [comment]
Also, feel free to update the README where it says "Currently only Standard diplomacy and Fleet Rome are supported." next time you work on it :)

**Comment by zond** [comment]
Deployed!

**Comment by tttppp** [comment]
Thanks for such a quick redeploy!

Good news: That fixed the issue, so that now I can issue hold orders.

Bad news: I can't attack or support.

The new error is with this bit of javascript:
```
			var trans = curr.getAttribute("transform");
			if (trans != null) {
				var transMatch = /^translate\(([\d.-]+),\s*([\d.-]+)\)$/.exec(trans);
				x += Number(transMatch[1]);
				y += Number(transMatch[2]);
			}
			curr = curr.parentNode;
```

I'm think the issue is that I used transform, but I used rotate, rather than translate.  I think this could need a painful fix.

**Comment by zond** [comment]
Ah, I see. I deployed again after your diplicity PR. Lets hope this fixes it :D

**Pull request merged**
