### PR TITLE
Remake classical map without a translation in it.

### PR DESCRIPTION
**Pull request by tttppp**
The classical map contained an [SVG translation](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) in it. This caused issues in lots of places:

* Firstly the diplicity code to display units and orders had to copy with it.
* The map tester code I wrote doesn't work for the existing classical map (although this doesn't really matter since we know it works).
* @spamguy had to work around it for a new client he's writing: https://github.com/spamguy/vue-dipl.io/commit/75adef7310dbd5d460edc75800e70f8f607999bb#commitcomment-25188753

In theory it should be really easy to just remove the translation by shifting all the coordinates in the original svg, however I couldn't find a tool to do this and when I had a go using inkscape then I broke the map.

So instead I created a new map from scratch using the variant generator.  As a bonus the svg size has gone down from 605k to 432k.

### CODE REVIEW

**Comment by tttppp** [comment]
The new map looks pretty similar to the old one (I kind of traced it).

The new map with nothing on it

**Comment by tttppp** [comment]
Actually the reduction in file size might be because I haven't included the font definition. I didn't include it in Cold War either - is that a bug?

**Comment by tttppp** [comment]
GitHub has a nice tool for seeing the differences between the old and new map: https://github.com/zond/godip/pull/30/files?short_path=50ed5a3#diff-50ed5a39457357b95d3bd0f0a9899337

**Comment by zond** [comment]
I like it, nice cleanup and not a lot of visible change :)

The font definition could become a problem - the reason I added it was that
some device or browser didn't have the exact same font, which made all
texts misaligned and ugly :/

I would recommend including it in all maps, if you want to ensure they look
the same everywhere.

**Comment by tttppp** [comment]
Ok - let's see what happens!

**Comment by zond** [comment]
Looks good. Commit at will!

Don't forget to roll out to the server as well :)

**Comment by tttppp** [comment]
It's live, and I just tested it. Looks good to me!

**Comment by zond** [comment]
Woohoo!

**Comment by spamguy** [comment]
I'm a little late to the party, but I just wanted to applaud @tttppp for the fix. I agree the backend looks a lot cleaner, the translation code is gone without affecting output, and it had the side effect of fixing Italian labels that were not translated correctly on my side.

Great job all!

screen shot 2017-11-20 at 8 36 34 am

**Comment by tttppp** [comment]
@spamguy Thanks for the feedback! Have you tested other map variants in your new vue client?

**Comment by spamguy** [comment]
Still waiting to get an Ancient Mediterranian game going to prove phase context renders correctly, but at minimum the maps themselves look great.

**Comment by zond** [comment]
We have 9 ancient med games going right now, according to
https://diplicity-engine.appspot.com/html/global-stats.html, e.g.
https://diplicity-engine.appspot.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAoK6TnwkM

**Pull request merged**
