### PR TITLE
Limited the possible convoyers to units not at source or destination.

### PR DESCRIPTION
**Pull request by zond**

### CODE REVIEW

**Comment by zond** [comment]
@tttppp look at this.

It have a hunch that it might fix https://github.com/zond/diplicity/issues/93 by not suggesting Baleares as move destination since the fleet in Baleares won't be a possible convoy candidate anymore.

If the option generation accepted Baleares as a destination, but the Move order validation didn't (because it was more thorough), that would cause the Internal Server Error in the original issue.

I'm not 100% sure though, since I don't know what the Internal Server Error looked like, and am not sure if the validation is stricter than the option generation.

**Comment by tttppp** [comment]
The comment you've added sounds like it should fix this issue.  In the game in question there was a fleet at the destination.  In the classical map there are no similar positions as there are no adjacent-but-unconnected land regions.

**Comment by zond** [comment]
That's my thought.

I don't have the energy or time to create a test case for this. If you do
I'd be obliged.

Also, if you have time to merge and deploy I'd be happy, since my keyboard
time for today has run out :)

**Comment by tttppp** [comment]
Ok great, I'll hopefully have a chance at the weekend.

**Comment by zond** [comment]
Cool, I'll do it next time I can otherwise, but I don't know when that'll
be :)

**Comment by tttppp** [comment]
I've added a test, but it fails. It seems to fail whether there's a fleet in Baleares or not.

**Comment by zond** [comment]
I'll take a look when I have the time... But I would suggest you (as the
creator of  ancient med variant :) try your hand as well :D

**Comment by tttppp** [comment]
Do you use an IDE for Go?  I've been using a combination of a text editor and find/grep to find references, and it's pretty slow progress!  I've been using fmt.Println for debugging, which is also pretty painful :-)  It would be nice to have some hints as to invalid syntax and type conflicts while writing the code. I'm sure a large part of the problem is my unfamiliarity with the language.

**Comment by zond** [comment]
For vim users (like me) https://github.com/fatih/vim-go is unbeatable.

I have also tried LiteIDE which is nice, and heard very good things about
IntelliJ with the go plugin.

**Comment by zond** [comment]
I noticed that the code I changed was only used when validating moves (which seemed to maybe work anyway, since the server returned an error when the illegal move was issued), not when producing move destinations.

I updated the test and the code that produces move destinations, see what you think!

**Comment by zond** [comment]
Awesome!

**Comment by tttppp** [comment]
Ok - this is weird. About 1 in 10 test runs I get a failure:

```
.../src/github.com/zond/godip/variants/ancientmediterranean$ for i in {0..9}; do go test -v | grep "_test.go"; done
	ancientmediterranean_test.go:73: There should be no option for Rome to move sag to bal
```

**Comment by zond** [comment]
Very weird :O

I wonder if it's
// Test there's no suggestion of a move from Saguntum to Baleares when the
destination is empty.
or
// Test there's no suggestion of a move from Saguntum to Baleares when the
destination contains a fleet.
that fails...

**Comment by tttppp** [comment]
I got LiteIDE working. The second assertion was failing.

As a workaround I've added a line to remove the fleet from ber before the final assertion. I've run this 100 times without seeing a failure.

So basically there's still some edge-case problem here, but at least the tests are reliable.

**Comment by zond** [comment]
I found the error!

Most of the path finding should never look at the same node twice, but in particular the convoy path finding should accept multiple paths containing the same node - after all, a fleet may be able to convoy to one destination but not another.

I made the graph pathfinder able to optionally allow revisiting the same node in multiple tried paths in https://github.com/zond/godip/commit/9aa41e352f57b6d2ba7d5e67e55adfbdc78fd226

**Comment by tttppp** [comment]
Nice! I'll deploy this when I get chance.

**Comment by zond** [comment]
Great!

**Pull request merged**
