### PR TITLE
Refactor reverse edge methods

### PR DESCRIPTION
**Pull request by tttppp**

### CODE REVIEW

**Comment by tttppp** [comment]
This might be easier to see here:
https://github.com/zond/godip/compare/5fe3173bf23eb758f2a1a325dbc575df51a1e809...5ca7e04ed1c130ab7f575f228922914573185ead
(ignore the changes to Cold War, which are unrelated to the directed edge code)

**Comment by tttppp** [comment]
If you want to make lots of comments then let me know. I can rebase the result onto the relevant reverts.  I'm a lot happier with this though. I couldn't decide whether to move PossibleMovesTo from orders/support (only  place it's used) to orders/move or not, so I elected for leaving it where it is.

**Comment by zond** [comment]
I think it looks good!

Nice cleanup :)

**Comment by zond** [comment]
I noticed that you make all functions take a "reverse" flag, but Graph still has both Edges and ReverseEdges?

**Comment by tttppp** [comment]
Good spot. I'll fix that. I got mixed up between SubNode.ReverseEdges (the slice needed for quick lookups) and Graph.ReverseEdges (not really needed).

**Pull request merged**
