### PR TITLE
Add svg flags for classical.

### PR DESCRIPTION
**Pull request by tttppp**
These are all based on flags from Wikipedia:
https://commons.wikimedia.org/wiki/File:Flag_of_Austria-Hungary_(1869-1918).svg
https://en.wikipedia.org/wiki/List_of_British_flags#/media/File:Naval_Ensign_of_the_United_Kingdom.svg
https://en.wikipedia.org/wiki/List_of_French_flags#/media/File:Flag_of_France.svg
https://en.wikipedia.org/wiki/List_of_German_flags#/media/File:War_Ensign_of_Germany_(1892%E2%80%931903).svg
https://en.wikipedia.org/wiki/List_of_Italian_flags#/media/File:Flag_of_Italy_(1861-1946)_crowned.svg
https://en.wikipedia.org/wiki/List_of_Russian_flags#/media/File:Standard_of_the_Emperor_of_Russia_(1858).svg
https://en.wikipedia.org/wiki/Flags_of_the_Ottoman_Empire#/media/File:Imperial_standard_of_the_Ottoman_Sultan.svg

Use these flags in other similar variants.

Also some minor refactoring for SVGUnits in the same classes.

### CODE REVIEW

**Comment by zond** [comment]
Very nice!

**Comment by zond** [comment]
(To be clear, merge whenever you like :)

**Comment by tttppp** [comment]
Thanks! I quite like giving myself some time before merging the change. For instance this time I realised that I should make all the SVGs have width 100%, height 100%, to allow them to fill whatever container the client uses.

**Comment by zond** [comment]
Sounds good :)

**Pull request merged**
