### PR TITLE
Create SVG map tester.

### PR DESCRIPTION
**Pull request by tttppp**
A test that uses the variant to create a folder of SVGs containing the
map in various states. For example shading all the supply centres to
check that owned supply centres will be visible to the players.

The generated SVGs must be manually inspected for correctness.

Note that this is a WIP - I cannot get the xml encoder to output anything.

### CODE REVIEW

**Comment by tttppp** [comment]
I've tried to implement the test I mentioned in #12, but I can't work out how to get the Go xml library to output anything to the file.  At one point I did have something being output, but all the supply centres were untouched by my regex replacement (I can't now work out how I did this).

I feel that being a complete newcomer to Go isn't helping my progress here!  Any suggestions would be welcome :-)

**Comment by zond** [comment]
I think you need to keep the file handle you get when you open the file, and close it after the encoder is done.

Also, since you discard errors it's hard for you to know what goes wrong :)

I would recommend either returning errors and treating them as test errors (recommended), or just panicking when they occur.

**Comment by tttppp** [comment]
Thanks - that was really helpful!  I hadn't noticed that I was swallowing the errors.

This is still WIP as I want to add a few more output images (selected provinces, units and orders). I also want to put the test in the variants directory, as ideally it should work against any/all variants.

**Comment by zond** [comment]
Very cool!

**Comment by tttppp** [comment]
This is now ready to go. It doesn't handle transforms (including translations), and the code is quite bulky. It does seem to work though.

supply_centers
This shows what the map looks like when the supply centers are owned.

selectable_provinces
This shows what all provinces look like when they are available to be selected. In particular I found with Pure that I'd rotated the provinces, and so the pattern used to be displayed at different angles for each province.

orders_land
This shows all the adjacent provinces by land. One of these is generated per edge type.

units_army_land
Finally this shows where the units will be displayed in the provinces. One of these is generated per province type, per unit type. This means that crazy combinations are generated (e.g. fleets on land) but since inspection is manual I don't think it really matters.  Trying to do something more complicated is hard as there can be arbitrarily complicated rules for when units are allowed in provinces (e.g. armies on arctic regions in winter, fleets in the same region in summer).

This last map also shows that the army in Constantinople is wonky - which matches what I saw in actual games. I guess I've rotated that supply center.

**Comment by tttppp** [comment]
I meant to also say that because it doesn't support translations then it doesn't work so well on the classical map. I don't think it matters too much, as I don't think we need to test it.

**Comment by zond** [comment]
Yeey! Amazing work!

**Pull request merged**
