### PR TITLE
Update pattern

### PR DESCRIPTION
**Pull request by JorenC**
@tttppp, I've updated this with the new highlight pattern. Could you try this on your local branch and check the actual effect in the discord chat?

@tttppp

### CODE REVIEW

**Comment by tttppp** [comment]
Superseded by #74.

**Comment by JorenC** [comment]
I updated the stripes pattern in all maps.

**Comment by JorenC** [comment]
@tttppp please check these maps, you can include them in your pull request.

**Comment by tttppp** [comment]
Looks good!  I'll merge the other PR and it should merge this automatically.

**Pull request merged**
