### PR TITLE
Updated NorthSeaWarsMap

### PR DESCRIPTION
**Pull request by JorenC**
Hi @tttppp,

It turns out that all the layers didn't have any ID (apparently Inkscape doesn't apply the label to the ID). 
That makes sense considering the orders and units didn't appear.

There are still quite some transforms in the foreground that I tried to remove, but that's a hell work with the border.
Can you try this updated version and see if the provinces work better?

I can still remove all the transforms, but with previous maps the script would ignore the foreground, so I'm hoping it won't come to that....

Thanks!
J

### CODE REVIEW

**Comment by tttppp** [comment]
This looks good to me.  I can't push to this branch, so I'm going to merge this and then fix the bindata file and svg version.

**Comment by JorenC** [comment]
Soooo @zond @tttppp I now have one PR with 2 changes.
I added all the 'classical' dependencies and the warmap. I'm not sure how to best proceed with this (new branch? Seems overkill for one file)...

**Comment by JorenC** [comment]
I've added and pushed dominance rules for two more maps. @tttppp maybe only copy+paste the map?

**Comment by tttppp** [comment]
I'm going to close this PR. Once #138 is merged then your branch will only "contain" the changes related to colouring provinces.

**Comment by JorenC** [comment]
I've moved these changes into a separate branch. After the NSW map is online, we can delete this branch.

**Pull request closed without merging**
