### PR TITLE
Updated armies/fleet

### PR DESCRIPTION
**Pull request by JorenC**
After Tom's last feedback

### CODE REVIEW

**Comment by zond** [comment]
I assume @tttppp will look at this?

**Comment by JorenC** [comment]
Yes, he did twice before, and somehow the position was a bit off - so I re-rendered this. Could ou assign him?

**Comment by zond** [comment]
Mentioning him like I did will make it email him about it :)

**Comment by JorenC** [comment]
@tttppp don't forget this one!

**Comment by tttppp** [comment]
Let's try it and see what happens!

**Pull request merged**
