### PR TITLE
Dominance rules when computing non-SC dominance

### PR DESCRIPTION
**Pull request by zond**
@JorenC, @tttppp, @johnpooch WDYT?

This should cover the variant-related hardcoding in https://github.com/zond/dipact/pull/273/files right?

### CODE REVIEW

**Comment by tttppp** [comment]
It looks fine. I've not investigated much, because I don't plan to use the feature, but is there a write up of the logic somewhere? Eg. If Austria takes Munich (but everything else stays the same) then does Burgundy suddenly stop belonging to France?

**Comment by zond** [comment]
@JorenC will have to answer these questions :D

**Comment by Wulfheart** [comment]
Could you also make a PR to the go library?

**Comment by JorenC** [comment]
Where do you want me to put the write-up?

Yes.
The influencedby describes the state in which the the province will change
to the normal rules, only if all are in effect (OR neutral SCs belong to
the dominator).

So if Austria picks Munich, Burgundy follows normal logic and becomes
contested (it is now a front line). If France captures Munich again, normal
logic applies and it becomes French (I'm disregarding Belgium for
simplicity's sake).
If Germany recaptures Munich, it becomes French again, like the start.
That's why I didn't only define the French influencing provinces but also
any other SCs that it's people are "long term friends with". While this is
maybe not ideal from the "we want to update the map as we go", it's the
cheapest because doesn't need knowledge of the game history, and these
events will less likely and to me totally acceptable - it's an aesthetic
feature only. Indeed, while watching through 10+ games it never came up as
something that stands out...

**Comment by zond** [comment]
> Could you also make a PR to the go library?

This is a PR to the go library?

**Comment by zond** [comment]
> Where do you want me to put the write-up?

Do you mean the rules? Check this code out and complete the ExtraDominanceRules in the classical configuration. Then if you want to play around with more variants you can add similar setups in them as well.

**Pull request merged**
