### PR TITLE
North Sea War Map

### PR DESCRIPTION
**Pull request by JorenC**
@tttppp I can't commit to the godip repo, so had to fork it. 

Added Coasts. Can't believe I missed that.

It _should_ all work now.

### CODE REVIEW

**Comment by tttppp** [comment]
I'm on my phone, but this looks wrong in the preview. Everything is black.

**Comment by JorenC** [comment]
Updated to have provinces invisible, should be ready to merge now.

**Comment by tttppp** [comment]
This doesn't have all the changes from master:
```
* 1d5d06f (JorenC/JorenNorthSeaWarsMap) Provinces invisible
* bda41c1 Added jut/ec and jut/wc
| * 1b0fe92 (HEAD -> master, origin/master, origin/HEAD) Revert "Merge pull request #138 from zond/NorthSeaWarsMap"
| * 4c96491 (tag: v0.1.89) Merge pull request #138 from zond/NorthSeaWarsMap
| * 0e1381d Make all of Sealand selectable.
| * 4611afa Remove id of sea from the sea.
|/  
* 89e425e Fix width and height to be 100%.
```

Ideally you need to revert 1b0fe92 and then add your changes:
```
git fetch origin
# This next command will throw away everything in your working directory, so make a copy of the svg if you need it.
git reset --hard origin/master
[Add your changes to the svg]
[Create a commit]
[Push to your fork]
```

**Comment by JorenC** [comment]
image

**Comment by JorenC** [comment]
How can there be conflicts after a hard reset and merge. I don't get it anymore

**Pull request closed without merging**
