### PR TITLE
Set IDs of supply center/province center/name SVG groups.

### PR DESCRIPTION
**Pull request by spamguy**
See #37.

### CODE REVIEW

**Comment by zond** [comment]
Looks good!

**Comment by spamguy** [comment]
Sweet, thanks! I'm trying to get the diplicity server to dispense the revised SVGs but I get only old, un-IDed SVGs. That is, calling http://localhost:8080/Variant/Classical/Map.svg returns an SVG with `<g id="layer6" inkscape:label="supply centers">`. I have purged local cache, killed and restarted the diplicity server, deleted diplicity and its dependencies and reinstalled, seemingly everything. Is there somewhere else the old version is being cached? `layer6` appears in none of the repos you own, so I'm stumped.

**Comment by zond** [comment]
Ah, someone has to deploy the new code for it to become live as well. @tttppp, do you have the time? :)

**Comment by tttppp** [comment]
Yes - also first the asset files need generating.  Let me try it now.

**Comment by tttppp** [comment]
Ok - it's deployed!  You'll have to clear your cache to see the updated maps. If you want to put something live for players to use then I think we might need to update the etag version number to tell clients to ignore their cached maps.

I have most of my map file generating script working now, so I'm hoping to put another variant live this month!

**Comment by zond** [comment]
Ah, it's good that you are livelier than me @tttppp, I had forgotten both the resource regeneration and the ETAG numbers :)

Cool with the map generating script! Looking forward to seeing it!

**Comment by spamguy** [comment]
@zond, @tttppp Sorry to bear bad news, but this deployment didn't help. After purging all the caches and things and visiting http://localhost:8080/Variant/France%20vs%20Austria/Map.svg (or any map, really), SVG groups still have the old IDs.

**Comment by zond** [comment]
Oh, you were running on localhost? Well then deploying wouldn't help or be
needed...

Do you have the latest godip code? Does it include the new generated
resources from
https://github.com/zond/godip/commit/b3720c1d31c5872e1fa26b2193705ce9c9ec16ec
? Have you restarted diplicity with the new godip code?

**Comment by spamguy** [comment]
I was wondering why localhost was using production as a dependency, but I was just going along with it...:)

I didn't see the go-bindata step, though. After pulling that commit and rerunning the IDs show up as expected. Next time I'll make sure to include regenerated assets in my commit. Thanks, all!

**Comment by zond** [comment]
Great :)

**Pull request merged**
