### PR TITLE
Update Waterloo (France vs Russia)

### PR DESCRIPTION
**Pull request by apauciulo**
It's correct? Thanks you.

### CODE REVIEW

**Comment by tttppp** [comment]
We had a look at the stats for France vs Russia and it is overwhelmingly in favour of Russia (roughly 95% of games are a Russia win).  Maybe you'd be interested in updating the map and starting units to try to make a fairer variant?

**Comment by apauciulo** [comment]
Hi, I trying the "WATERLOO" variant with a piece more on the France (by putting a fleet in Bel), but again the Russia has unbalance in favor. I wil try with other version of the "WATERLOO" variant.

**Comment by JorenC** [comment]
Should we close this PR - it's dead for a year, and France vs Russia is likely imbalanced

**Comment by zond** [comment]
If we remove one army from Russia before start maybe?

**Comment by tttppp** [comment]
Closing this PR too. We can always revisit it if it seems like an interesting variant.

**Pull request closed without merging**
