### PR TITLE
WIP: Support trade centers

### LINKED ISSUE #47: Supporting units to trade centers from CNS does not work in North Sea Wars
As explained in this thread: https://groups.google.com/forum/#!topic/diplicity-talk/yMS98tRgiWA

> a fleet in Iron, Grain, or Wood, cannot support a fleet from CNS to one of the other trade routes

The same is true for supporting moves via convoy too.

### PR DESCRIPTION
**Pull request by tttppp**
Fixes #47

### CODE REVIEW

**Comment by tttppp** [comment]
This currently works for simple moves, but not support for convoyed moves.

**Comment by tttppp** [comment]
Is there an easy way to check if I've broken the performance?  I was thinking of deploying it and seeing if we get lots of complaints!

**Comment by zond** [comment]
What are reverse edges? And why are support orders resolved using a new function?

**Comment by tttppp** [comment]
North Sea Wars has some one-way edges that lead to the trade centers. The support code (for options) previously worked based on finding paths from the destination to the source. The validator code was already correct though.

**Comment by tttppp** [comment]
The ReverseEdges (assuming they're created using Conn) are the reverse of the Edges:

```	self.Edges[target.getName()] = &edge{
		sub:   target,
		Flags: flagMap,
	}
	target.ReverseEdges[self.getName()] = &edge{
		sub:   self,
		Flags: flagMap,
	}
```

**Comment by zond** [comment]
Ah, alright - so this adds support for one-way edges that you want to use in NSW to implement them?

Fair enough.

I would be surprised if this has any performance implications, but the easiest way is to run the tests in https://github.com/zond/godip/tree/master/variants/classical/droidippy and time how fast it is before and after.

I recommend having the ENV var BENCHMARK_OPTIONS=true to also run the options calculations, since they are often the worst performance offender.

**Comment by tttppp** [comment]
Neat feature - I didn't realise the full game tests could do this.

**Comment by zond** [comment]
Oh, also set DEBUG=true to get timings for regular resolves. Quite handy when you suspect performance regression.

See https://github.com/zond/godip/blob/master/variants/testing/games_testing.go#L275 for what happens :)

**Comment by tttppp** [comment]
There doesn't seem to be an issue with performance, so merging this part. The support for convoys is still broken, but that's much less common.

Also as a side note I noticed that using BENCHMARK_OPTIONS=true causes validation of the options, which are actually computed incorrectly (before this change). For some reason the tests seem to think that a unit can move via convoy to the same spot, and an army can move via convoy to a sea space.  This is never suggested in a real game, so I assume it's an issue with the test framework.  I'll raise a separate bug for this.

**Comment by zond** [comment]
Ah, true. Nice to create the bug.

Adding support of this to convoys should be sort of similar to adding it to supports, no?

**Comment by tttppp** [comment]
Yeah - it's similar, but I couldn't face duplicating a whole load more code. I didn't fix this in a nice way :disappointed:

**Comment by tttppp** [comment]
Issue for benchmark options raised here: #49

**Comment by zond** [comment]
One suggestion would be to refactor the Support support (hah) to use the same method, but use a parameter to select from-edges or to-edges. That would be less duplication.

To simplify that, do the same thing with the Graph function that returns edges - a parameter that selects to- or from-edges.

And then, of course, do the same thing for the Convoy-calculating functions.

**Pull request merged**
