### PR TITLE
Fixes #14: Ancient Mediterranean variant

### LINKED ISSUE #14: Create Ancient Mediterranean Variant
This is a five player game on a custom map. The full rules are [here](http://www.dipwiki.com/?title=Ancient_Mediterranean) and they are the same as the base game, but with a different adjacency.  I wanted to implement this because it's a different map, a different number of players and because it's gets [played quite a lot](http://vdiplomacy.net/variants.php?).

I am planning to make Baleares a non-convoy space as is done [here](http://webdiplomacy.net/variants.php#AncMed).

I have started on the map, and it currently looks like this:

ancientmediterraneanmap svg_1

It needs more work to make canals clearer, and I haven't created the province layer yet.  Any suggestions welcome, although I can't promise I'll do them as creating the map is (as expected) time consuming!

### PR DESCRIPTION
**Pull request by tttppp**
Fixes #14.

### CODE REVIEW

**Comment by tttppp** [comment]
This still needs some work to finish the highlights for non-supply-center provinces. I wanted to get the PR created as the code can be reviewed, and it would be good to get a second pair of eyes on the connections and sea/land flags.

For reference, here is a wiki page with the variant described on it: http://www.dipwiki.com/?title=Ancient_Mediterranean

Here are the coloured in supply centre regions:

supply_centers

Here are the movement options on land:

orders_land

Here are the moment options by sea:

orders_sea

Here are the places an army can go:

units_army_land

Here are the places a fleet can go:

units_fleet_sea

**Comment by tttppp** [comment]
Also I want to add some specific test cases and a test game or two, as you did for Classical, to check the code is probably right.

In particular I want to test what happens when attempting to convoy via Baleares.

**Comment by zond** [comment]
Highlights for non SC provinces? When are they highlighted?

I was under the impression it needed some kind of special rules?

**Comment by tttppp** [comment]
The highlights are for when showing valid moves to the player. It's the diagonal red stripes pattern.

Ancient med needs no special rules, with the possible exception of convoys through Baleares. It has a few crossover points in the map (it's not a planar graph) but it's otherwise very similar to classical.

**Comment by tttppp** [comment]
Another note to myself: I need to check the supply centre markers in Thebes and Cirta as units there don't seem centralised.

**Comment by zond** [comment]
Ah, those highlights :)

But the PR looks good. I can't vouch for the graph etc, but there are always bugs to iron out. Merge when you feel ready! :D

**Comment by tttppp** [comment]
I've fixes Thebes and Cirta and the canal near Reed Sea.  I've written some unit tests for certain bits of the map. I need to:

- [ ] Finish the province regions in the svg.
- [ ] Decide which ruling to go with about convoys via Baleares (easy vs correct).
- [ ] Write rules for the variant (even though these aren't yet used by any client).
- [ ] Add a DATC style test game.
- [ ] Test with Diplicity locally.

**Comment by tttppp** [comment]
Added a whole game test in the style of the droiddippy tests (not the DATC tests).

**Comment by zond** [comment]
Cool :)

Note that the Droidippy tests you are talking about are actually generated from real Droidippy games. It's a fun fact that after fixing a few errors they started showing me errors in the Droidippy adjudicator instead :D

**Comment by tttppp** [comment]
Yes - I assumed they must be the real games!  They showed me a couple of issues with my map, and many, many issues with my python game format conversion script!

**Comment by tttppp** [comment]
The only thing left now is to investigate how easy it is to change the convoy rules for Balaeres. It's meant to be a set of islands inhabitable by an army or a fleet, but the fleet is considered to be at sea for convoys.

Another implementation I saw scrapped this rule presumably because it was an oddity and different from classical.

Do you have an idea how much work this would be to implement properly?

**Comment by zond** [comment]
Right now I believe the presence of the flag `Land` is what actually turns convoying off.

You might add a new flag, `ConvoyableLand` or something (better names are welcome!) and modify lots of parts of classical/common/common.go, classical/orders/convoy.go and .../move.go (everything that handles possible and concrete movement and convoy paths and orders) to check for that flag even if the `Land` flag is set. You probably have to re-run (and possibly add, at least for the new flag) tests for Move and Convoy orders as well).

**Comment by tttppp** [comment]
I've managed to get Baleares to be convoyable by inventing a new flag to explicitly say a region can be convoyed through. I also created an Archipelago flag for coastal convoyable regions (I thought about putting this in the ancient med package, but I thought it's easier to understand when it's with the other flags in classical).

I've run all the tests I could find, including the droidippy tests (although one or two of these always fail for me - with or without my changes). The gae tests also failed, as always (I'm not sure what this package is for - do the tests need fixing?)

I'm ready to merge, but wanted a review of the changes to classical when you get chance.  Please merge if you're happy with that bit (and anything else you want to review).  Thanks!

**Comment by tttppp** [comment]
Just bumping this to say that unless there are objections I'm going to merge this during the weekend. :-)

**Comment by zond** [comment]
Sounds good!

If you want I'll make you dev in the App Engine project so you can roll it out too?

**Comment by zond** [comment]
(I'm on vacation and not near a keyboard)

**Comment by tttppp** [comment]
Cool! Enjoy your holiday! Yes, being able to roll out (/back) the changed would be great. Thank you!

**Pull request merged**
