### PR TITLE
Updated Ancient Medditeranean fonts

### PR DESCRIPTION
**Pull request by JorenC**
There is an old commit of Vietnam War map in this, it's very old. 

I added the fonts and redid the labels to make the map feel more ancient medditerranean.

### CODE REVIEW

**Comment by tttppp** [comment]
Do you want to keep the Ancient Mediterranean changes, but not keep the Vietnam War changes?

**Comment by JorenC** [comment]
Yes, the Vietnam war changes are from 5 mo ago when we changed that map,
and I don't know how to "remove" them from the request.

I'm a bit worried the embedded font doesn't show, I think in the @font face
part the name should be defined the same as in the text layers for the
seas, there might be some issues with "Antiqua Scribe" Vs Antiqua Scribe.
Maybe replace all and just call it antiquascribe ?

**Comment by tttppp** [comment]
I tried a few things, but couldn't get the embedded font to appear. I checked with a couple of different svg renderers.

**Comment by JorenC** [comment]
I'll try again this weekend, thanks for the help!

**Pull request closed without merging**
